### ISSUE TITLE
啊，就这么夭折了么= =

### ISSUE THREAD

**Issue by zxteloiv** [stormzhang/1024#29]
感觉好可惜啊....
不过杯子难洗也不是不能接受，要是能有个折衷产品就好了，毕竟吃蛋白粉的时候也是很难洗的，但用筷子或什么戳一下也就没问题了。

**Comment by stormzhang** [comment]
非常感谢你的支持，项目夭折不只是产品本身的问题，还有公司战略层面，我们还是认为把工作重心聚焦在我们80%的用户身上来。

**Comment by hax** [comment]
悲剧。。。

**Comment by zxteloiv** [comment]
理解... 就是比较可惜，之前试过薄荷的超模25感觉很好喝，就是不扛饿。
这个准备试试若饭的。
